### ISSUE TITLE
Testimonials Widget 3.1.0 not working

### ISSUE THREAD

**Issue by qjones3** [michael-cannon/testimonials-widget#175]
Hi, I just upgraded to version 3.1.0 and it no longer rotates. Instead, it displays all the testimonials. I upgraded to Wordpress 4.2.1, but no change.

Please help,
Quinton

**Comment by michael-cannon** [comment]
Please try 3.1.1. The WordPress SVN repository had missing directories.

**Comment by michael-cannon** [comment]
Others report that 3.1.1 fixes the missing file folders issue which caused the rotation to stop working.
