### ISSUE TITLE
Version 3.1.0 not working

### ISSUE THREAD

**Issue by VinceScript** [michael-cannon/testimonials-widget#176]
Hi, I just upgraded to version 3.1.0 and it no longer rotates. Instead, it displays all the testimonials. I upgraded to Wordpress 4.2.1, but no change.

Please help,
Andy

**Comment by luminously7** [comment]
+1  Same problem.  Error in console. 
- ...libraries/bxslider-4/dist/jquery.bxslider.css?ver=4.2.1 Failed to load resource
- ...bxslider-4/dist/jquery.bxslider.min.js?ver=4.1.2 Failed to load resource
-...includes/libraries/bxslider-4/dist/jquery.bxslider.css?ver=4.2.1 Failed to load resource: the server responded

**Comment by michael-cannon** [comment]
I'm sorry about the troubles. Got URLs to see the problems at?

**Comment by michael-cannon** [comment]
Please 3.1.1 from here, https://github.com/michael-cannon/testimonials-widget/tree/3.1.1, or WordPress Plugins. There were missing directories in the SVN repository.

**Comment by luminously7** [comment]
That fixed it.  Thank you
