### ISSUE TITLE
Include the script at the end of body or make it configurable

### ISSUE THREAD

**Issue by nitinsurana** [michael-cannon/testimonials-widget#182]
hi,

I have lots of plugins on my website and every one keeps adding scripts to the head tag, due to which the page rendering takes a lot of time. It'll be really appreciable if this option can be configurable in the plugin settings or if possible, the code can be modified to append the script in the footer by default.

https://wordpress.org/support/topic/satisfactory-so-far?replies=2#post-7020492

**Comment by michael-cannon** [comment]
This is already the case for Testimonials Widget.

* https://github.com/michael-cannon/testimonials-widget/blob/master/includes/class-testimonials-widget.php#L753
* https://github.com/michael-cannon/testimonials-widget/blob/master/includes/class-testimonials-widget.php#L757
