### ISSUE TITLE
Add a little bit of right padding to `join-` class

### ISSUE THREAD

**Issue by michael-cannon** [michael-cannon/testimonials-widget#186]
There's no padding after the commas. It might be a simple theme issue or maybe not CSS'd at all. I suggest just a small em or px amount. E.g. 0.1em or 2px.

E.g. https://axelerant.com/services/drupal-talent-augmentation/

![screen shot 2015-10-12 at 09 26 28](https://cloud.githubusercontent.com/assets/1872498/10429036/8b91e366-70c3-11e5-9979-df4c804d9c08.png)

**Comment by michael-cannon** [comment]
Per https://github.com/michael-cannon/testimonials-widget/blob/master/assets/css/testimonials-widget.css#L88, `join-*` has a space after the comma. This might be a theme issue then. Any other examples where this is failing?

**Comment by subharanjanm** [comment]
@michael-cannon It seems like an issue with the current theme because the same is working fine with the default `TwentyFifteen` theme. https://www.evernote.com/l/AP5qJuLk5q5Oe6z6A2GxgyIsa9kI9b9EMsY

**Comment by saurabhsirdixit** [comment]
@michael-cannon @subharanjanm : I have tested this with 2-3 test sites using with different themes and its working fine for all. So it seems like mentioned issue is with particular theme and for that we can add style in child theme style.css. Something like : 
  {
  padding-right: 0.5em;
}

**Comment by michael-cannon** [comment]
Ah, non-issue.
