### ISSUE TITLE
cannot click on testimonial to see full post

### ISSUE THREAD

**Issue by habanbo** [michael-cannon/testimonials-widget#189]
I can see the testimonials on the page but I cannot click on them to see the full post, the testimonial on page showing a certain number of characters but my full testimonial is longer than that.

how can users check the full post.

**Comment by subharanjanm** [comment]
Hi Habanbo,

Thanks for reaching out.

We have a "Read More" link option for the testimonials which is a premium feature in [Testimonials Widget Premium](https://store.axelerant.com/downloads/best-wordpress-testimonials-plugin-testimonials-premium/) . Please check the features list in the above link to find out more.

However, you can add links to individual testimonials by using the filters provided with the plugin. Please find the list of hooks(actions & filters) to customize the output as needed: https://github.com/michael-cannon/testimonials-widget/blob/master/API.md 

[Please follow the link to know how to customize the testimonial list and widget output?](https://nodedesk.zendesk.com/hc/en-us/articles/202380281)

Please let me know if you need any further assistance.

Thanks !!

**Comment by subharanjanm** [comment]
Hi Habanbo,

I hope your query has been answered above. For now, we're considering this issue as closed.

If I can be of any assistance, please do not hesitate to contact me.

Thanks,
Subh
